### ISSUE TITLE
Carat 1 px border looks lighter than container border

### ISSUE THREAD

**Issue by caheberer** [mistergone/cf-tooltips#8]
This may be the accurate color? They should both be Dark Gray.

**Comment by mistergone** [comment]
They're the same color (#43484e). I'm not an expert, but I think it's a weird effect of 1px diagonal lines (the size makes them difficult to anti-alias), and a 1px line at 45° is basically the worst case scenario of anti-aliasing. We could darken the color to try to counter the illusion, but that's about the only solution I know of.

But you're not crazy - I see exactly the effect you're seeing.

**Comment by caheberer** [comment]
Got it, could you take a shot at darkening it so that it appears to be the same?

**Comment by mistergone** [comment]
I will try to do some research on offsetting colors for anti-aliasing - I don't think this is the only time this will come up, so we should try to have some design and front-end discussions around this issue.

**Comment by caheberer** [comment]
True, probably good to check first.

**Comment by mistergone** [comment]
I've consulted with front-ends, and the general feeling is there's nothing to be done about this. I'll continue to keep my eyes open to see if anyone on the web talks about this, but otherwise, I'm just going to close this issue.
